### PR TITLE
improvement to sintra areas

### LINKED ISSUE #457: improvement to sintra areas
OESTE
LABEL:N039.20.35.265:W009.46.52.083
N038.54.00.000:W010.00.00.000
N039.20.55.000:W009.47.05.000
N039.20.55.000:W009.26.35.480
N039.02.31.980:W009.31.32.710
N038.47.40.000:W009.35.20.000

NORTE
LABEL:
N039.02.31.980:W009.31.32.710
N039.20.55.000:W009.26.35.480
N039.20.55.000:W008.57.21.860
N039.08.51.590:W009.07.08.060
N038.58.38.610:W009.12.38.080

SUL
LABEL:
N038.47.40.000:W009.35.20.000
N039.02.31.980:W009.31.32.710
N038.58.38.610:W009.12.38.080
N038.46.10.200:W009.19.18.700
N038.46.00.236:W009.19.44.749
N038.45.33.276:W009.21.08.494
N038.45.16.830:W009.22.36.635
N038.45.11.304:W009.24.07.000
N038.45.16.830:W009.25.37.366
N038.45.33.000:W009.27.09.000

ESTE
LABEL:N039.20.38.240:W008.57.10.290
N038.46.10.200:W009.19.18.700
N038.58.38.610:W009.12.38.080
N039.08.51.590:W009.07.08.060
N039.20.55.000:W008.57.21.860
N039.20.55.000:W008.55.05.000
N039.08.10.000:W009.05.25.000
N038.57.38.000:W009.11.04.000
N038.56.55.000:W009.11.27.000
N038.49.40.000:W009.15.19.000
N038.49.16.529:W009.15.32.303
N038.48.16.417:W009.16.19.665
N038.47.24.000:W009.17.17.000
N038.47.22.819:W009.17.18.534
N038.46.37.052:W009.18.27.461

### PR DESCRIPTION
**Pull request by becas22**
fixes #457

@pinatacolada depois dá a tua opiniao sobre o schedule de ativação

### CODE REVIEW

**Comment by pinatacolada** [comment]
falta saber a que horas devem aparecer, a que horas e quais as areas que o limite superior sobe e o que acontece quando ha FUA de R42B ate 245 em AUP

**Comment by becas22** [comment]
Sugeria dar merge como está e depois refinar. Assim ficava pronto para um eventual pre-release

**Comment by becas22** [comment]
Ativação
seg-sex 09-17
NORTE, SUL e OESTE 000-040 com fill
ESTE 000-030 sem fill

**Comment by becas22** [comment]
AREA:4:R42BO
LABEL:N039.20.35.265:W009.46.52.083:R42BO
LIMITS:010:030
ACTIVE:1
N038.54.00.000:W010.00.00.000
N039.20.55.000:W009.47.05.000
N039.20.55.000:W009.26.35.480
N039.02.31.980:W009.31.32.710
N038.47.40.000:W009.35.20.000

AREA:4:R42BN
LABEL:N039.20.34.324:W009.26.16.315:R42BN
LIMITS:010:030
ACTIVE:1
N039.02.31.980:W009.31.32.710
N039.20.55.000:W009.26.35.480
N039.20.55.000:W008.57.21.860
N039.08.51.590:W009.07.08.060
N038.58.38.610:W009.12.38.080

AREA:4:R42BS
LABEL:N039.01.40.272:W009.31.02.671:R42BS
LIMITS:010:030
ACTIVE:1
N038.47.40.000:W009.35.20.000
N039.02.31.980:W009.31.32.710
N038.58.38.610:W009.12.38.080
N038.46.10.200:W009.19.18.700
N038.46.00.236:W009.19.44.749
N038.45.33.276:W009.21.08.494
N038.45.16.830:W009.22.36.635
N038.45.11.304:W009.24.07.000
N038.45.16.830:W009.25.37.366
N038.45.33.000:W009.27.09.000

AREA:4:R42BE
LABEL:N039.20.38.240:W008.57.10.290:R42BE
LIMITS:010:030
ACTIVE:1
N038.46.10.200:W009.19.18.700
N038.58.38.610:W009.12.38.080
N039.08.51.590:W009.07.08.060
N039.20.55.000:W008.57.21.860
N039.20.55.000:W008.55.05.000
N039.08.10.000:W009.05.25.000
N038.57.38.000:W009.11.04.000
N038.56.55.000:W009.11.27.000
N038.49.40.000:W009.15.19.000
N038.49.16.529:W009.15.32.303
N038.48.16.417:W009.16.19.665
N038.47.24.000:W009.17.17.000
N038.47.22.819:W009.17.18.534
N038.46.37.052:W009.18.27.461

**Pull request closed without merging**
